=== Erika14burgos/Bryan_Cafe_EB/menu.dtd
<!ELEMENT menu (meals, beverages)>
<!ELEMENT meals (item+)>
<!ELEMENT item (name, price, description?, image?)>
<!ELEMENT beverages (coffee, other)>
<!ELEMENT coffee (size+)>
<!ELEMENT size (name, price, description?)>
<!ELEMENT other (item+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT image (#PCDATA)>

=== Erika14burgos/Bryan_Cafe_EB/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE menu SYSTEM "menu.dtd">
<menu>
    <meals>
        <item>
            <name>Beetroot and feta salad</name>
            <price>$15.00</price>
            <description>Suitable for vegetarians, made with fresh beetroot</description>
            <image>images/beetroot_salad.jpg</image>
        </item>
        <item>
            <name>Sourdough Rye Sandwich</name>
            <price>$18.00</price>
            <description>Cheese and salad sandwich made with organic, sourdough rye bread</description>
            <image>images/sourdough_sandwich.jpg</image>
        </item>
        <item>
            <name>Spinach Pie and Salad</name>
            <price>$20.00</price>
            <description>Tasty pie with salad</description>
            <image>images/spinach_pie.jpg</image>
        </item>
        <item>
            <name>Feta pancakes with salad</name>
            <price>$19.50</price>
            <description>Tasty pancake filled with feta and salad</description>
            <image>images/feta_pancakes.jpg</image>
        </item>
    </meals>
    <beverages>
        <coffee>
            <size>
                <name>Small</name>
                <price>$3.50</price>
                <description>For coffee, please inform the staff of the coffee type.</description>
                <image>images/coffeeS.jpg</image>
            </size>
            <size>
                <name>Regular</name>
                <price>$4.00</price>
                <image>images/coffeeM.jpg</image>
            </size>
            <size>
                <name>Large</name>
                <price>$4.50</price>
                <image>images/coffeeL.jpg</image>
            </size>
        </coffee>
        <other>
            <item>
                <name>Soda</name>
                <price>$3.00</price>
                <image>images/soda.jpg</image>
            </item>
            <item>
                <name>Fresh juice</name>
                <price>$6.00</price>
                <image>images/fresh_juice.jpg</image>
            </item>
            <item>
                <name>Bottled water</name>
                <price>$2.00</price>
                <image>images/bottled_water.jpg</image>
            </item>
        </other>
    </beverages>
</menu>
